filegroup(
    name = "srcs",
    srcs = [
        "CustomLayout",
        "DetectLanguage",
        "HelloWorld",
        "InheritLibFolder",
        "InheritSameFolder",
        "LanguageByAttribute",
        "LanguageByOption",
        "NamespaceByAttribute",
        "NamespaceByConvention",
        "NamespaceByGrammar",
        "NamespaceGrammarOverConvention",
    ],
    visibility = ["//visibility:public"],
)
