filegroup(
    name = "srcs",
    srcs = [
        "Cpp",
        "DetectLanguage",
        "ImportGenerated",
        "InheritLibFolder",
        "InheritSameFolder",
        "Java",
        "LanguageByAttribute",
        "ObjC",
        "Python2",
        "Python3",
    ],
    visibility = ["//visibility:public"],
)
